name: Build APK Debug

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare Debug Keystore
        run: |
          if [ -f debug.keystore.base64 ] && [ ! -f debug.keystore ]; then
            base64 -d debug.keystore.base64 > debug.keystore
          fi

      - name: Build Debug APK
        run: |
          if [ -n "$JAVA_HOME_17_X64" ]; then
            export JAVA_HOME="$JAVA_HOME_17_X64"
            export PATH="$JAVA_HOME/bin:$PATH"
          fi
          gradle :app:assembleDebug
